[package]
name = "aniy"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
ndarray = "0.15.6"
open = "5.1.2"
rayon = "1.10.0"
resvg = "0.41.0"
svg = "0.17.0"
video-rs = { version = "0.7.3", features = ["ndarray"] }
